; Inno Setup script for the Ember Forge editor.
;
; Build with scripts\Windows\BuildInstaller.bat, which stages the payload first. Do not run ISCC
; directly unless build\stage and build\version.iss already exist.
;
; Pass /DSIGN to sign the installer and uninstaller once a certificate is configured.

; Generated by Stage.bat from Ember/src/Ember/Core/Version.h, so the version lives in exactly one place.
#include "..\build\version.iss"

#define AppName "Ember Forge"
#define AppPublisher "Connor Shore"
#define AppURL "https://github.com/ConnorShore/Ember"
#define AppExeName "Ember-Forge.exe"

[Setup]
; This GUID is this application's identity - it is how Inno recognises an upgrade rather than a
; second install, and how the Apps & Features entry is keyed. Never change it.
AppId={{01F5433C-9854-4801-B4DA-2DA32C509A79}
AppName={#AppName}
AppVersion={#AppVersionFull}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}/issues
VersionInfoVersion={#AppVersionNumeric}

; {autopf} is Program Files for an all-users install and %LocalAppData%\Programs for a per-user one.
; PrivilegesRequired=lowest with OverridesAllowed=dialog means the user is asked which they want
; instead of every install demanding an admin prompt.
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
AllowNoIcons=yes
DisableProgramGroupPage=auto

; The editor needs OpenGL 4.5 and is x64 only.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

WizardStyle=modern dynamic
LicenseFile=..\LICENSE
Compression=lzma2/max
SolidCompression=yes

; Authored alongside the other branding assets; Stage.bat also copies it to {app}\EmberProject.ico.
SetupIconFile=..\Ember-Forge\assets\images\EmberIcon.ico
UninstallDisplayIcon={app}\EmberProject.ico
UninstallDisplayName={#AppName}

; Required for the [Registry] association below to take effect promptly: it makes Setup broadcast
; SHCNE_ASSOCCHANGED, without which Explorer keeps drawing the previous (generic) .ebproj icon from
; its cache until the next logon.
ChangesAssociations=yes

OutputDir=..\build\installer
OutputBaseFilename=EmberForge-{#AppVersionFull}-Setup

; No VC++ redistributable step: every vendored library is a static lib and the Dist configuration
; sets staticruntime "On", so the payload contains no DLLs at all.

#ifdef SIGN
; Expects a "sign" tool defined in the Inno Setup IDE (Tools > Configure Sign Tools) or in
; ISPPBuiltins - see docs/Distribution.md.
SignTool=sign
SignedUninstaller=yes
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Unchecked by default; a desktop icon should be opt-in.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "associateproject"; Description: "Associate .ebproj project files with {#AppName}"; GroupDescription: "File associations:"

[Files]
Source: "..\build\stage\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Ember-Forge.exe carries its own icon resource (Ember-Forge\EmberForge.rc), so IconFilename is only
; belt-and-braces here - it pins the shortcuts to a known-good .ico regardless of the build.
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\EmberProject.ico"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\EmberProject.ico"; Tasks: desktopicon

[Registry]
; HKA resolves to HKLM for an all-users install and HKCU for a per-user one, matching whichever mode
; the user picked. uninsdeletekey removes the association on uninstall.
Root: HKA; Subkey: "Software\Classes\.ebproj"; ValueType: string; ValueName: ""; ValueData: "Ember.Project"; Flags: uninsdeletevalue uninsdeletekeyifempty; Tasks: associateproject
; Without this Windows invents its own "ebproj_auto_file" ProgId the first time the user picks an app
; from Open With, and that one has no DefaultIcon - which is the generic white page icon.
Root: HKA; Subkey: "Software\Classes\.ebproj\OpenWithProgids"; ValueType: string; ValueName: "Ember.Project"; ValueData: ""; Flags: uninsdeletevalue uninsdeletekeyifempty; Tasks: associateproject
Root: HKA; Subkey: "Software\Classes\Ember.Project"; ValueType: string; ValueName: ""; ValueData: "Ember Project"; Flags: uninsdeletekey; Tasks: associateproject
; Quoted because the default install path contains a space; PathParseIconLocation strips the quotes
; before splitting off an icon index, so an unquoted path with spaces can silently fail to resolve.
Root: HKA; Subkey: "Software\Classes\Ember.Project\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\EmberProject.ico"""; Flags: uninsdeletekey; Tasks: associateproject
Root: HKA; Subkey: "Software\Classes\Ember.Project\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#AppExeName}"" ""%1"""; Flags: uninsdeletekey; Tasks: associateproject

; Lets Windows find the editor by name, e.g. from Start > Run.
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\{#AppExeName}"; ValueType: string; ValueName: ""; ValueData: "{app}\{#AppExeName}"; Flags: uninsdeletekey

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; Deliberately no [UninstallDelete] for {localappdata}\EmberForge: the user's editor layout, logs and
; recent-project list should survive an uninstall and reinstall.
